/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as AulasRouteImport } from './routes/aulas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AulasIdRouteImport } from './routes/aulas.$id'

const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const AulasRoute = AulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AulasIdRoute = AulasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AulasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aulas': typeof AulasRouteWithChildren
  '/quiz': typeof QuizRoute
  '/aulas/$id': typeof AulasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aulas': typeof AulasRouteWithChildren
  '/quiz': typeof QuizRoute
  '/aulas/$id': typeof AulasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aulas': typeof AulasRouteWithChildren
  '/quiz': typeof QuizRoute
  '/aulas/$id': typeof AulasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aulas' | '/quiz' | '/aulas/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aulas' | '/quiz' | '/aulas/$id'
  id: '__root__' | '/' | '/aulas' | '/quiz' | '/aulas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AulasRoute: typeof AulasRouteWithChildren
  QuizRoute: typeof QuizRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aulas': {
      id: '/aulas'
      path: '/aulas'
      fullPath: '/aulas'
      preLoaderRoute: typeof AulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aulas/$id': {
      id: '/aulas/$id'
      path: '/$id'
      fullPath: '/aulas/$id'
      preLoaderRoute: typeof AulasIdRouteImport
      parentRoute: typeof AulasRoute
    }
  }
}

interface AulasRouteChildren {
  AulasIdRoute: typeof AulasIdRoute
}

const AulasRouteChildren: AulasRouteChildren = {
  AulasIdRoute: AulasIdRoute,
}

const AulasRouteWithChildren = AulasRoute._addFileChildren(AulasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AulasRoute: AulasRouteWithChildren,
  QuizRoute: QuizRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
